# Copilot repository instructions
# This file documents required actions for Copilot-generated changes.
# NOTE: Copilot itself may not execute scripts. These instructions are
# mandatory for humans and automation to run after Copilot changes.

run_checks:
  - path: ".github/scripts/run_copilot_checks.sh"
    description: "Run this script after any code generation or modification by Copilot. It runs go mod tidy, tests with coverage, and enforces coverage baseline."

rules:
  - follow_best_practices: true
  - require_tests: true
  - require_benchmarks: true
  - require_examples: true
  - go_version: 1.25
  - module_path_must_reflect_repo: true
  - source_files_under_src: true

message: |
  Every time Copilot changes or generates code in this repository, the responsible agent
  MUST run the script: .github/scripts/run_copilot_checks.sh
  This enforces tests, coverage, and module tidiness.

